### ISSUE TITLE
Build failure with multi-ghc-travis

### ISSUE THREAD

**Issue by bitemyapp** [hvr/multi-ghc-travis#5]
https://github.com/bitemyapp/bloodhound/blob/master/.travis.yml

Log below.

```
Using worker: worker-linux-3-2.bb.travis-ci.org:travis-linux-10
$ export GHCVER=7.6.3
git.1
$ git clone --depth=50 --branch=master git://github.com/bitemyapp/bloodhound.git bitemyapp/bloodhound
Cloning into 'bitemyapp/bloodhound'...
remote: Counting objects: 240, done.
remote: Compressing objects: 100% (123/123), done.
remote: Total 240 (delta 127), reused 222 (delta 112)
Receiving objects: 100% (240/240), 189.48 KiB | 0 bytes/s, done.
Resolving deltas: 100% (127/127), done.
Checking connectivity... done.
$ cd bitemyapp/bloodhound
git.3
$ git checkout -qf f6827a0a867251febc890fcc6fbc88eff7a91b94
$ sudo service elasticsearch start
 * Starting Elasticsearch Server       ission denied on key 'vm.max_map_count'
$ sleep 3
$ rvm use default
Using /home/travis/.rvm/gems/ruby-1.9.3-p545
$ ruby --version
ruby 1.9.3p545 (2014-02-24 revision 45159) [x86_64-linux]
$ rvm --version
rvm 1.25.25 (latest-minor) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ gem --version
2.2.2
$ bundle --version
Bundler version 1.6.1
before_install.1
$ sudo add-apt-repository -y ppa:hvr/ghc
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/softwareproperties/ppa.py", line 95, in run
    self.add_ppa_signing_key(self.ppa_path)
  File "/usr/lib/python2.7/dist-packages/softwareproperties/ppa.py", line 105, in add_ppa_signing_key
    ppa_info = get_ppa_info_from_lp(owner_name, ppa_name)
  File "/usr/lib/python2.7/dist-packages/softwareproperties/ppa.py", line 83, in get_ppa_info_from_lp
    return json.loads(lp_page)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
before_install.2
$ sudo apt-get update
Ign http://downloads-distro.mongodb.org dist InRelease
Get:1 http://downloads-distro.mongodb.org dist Release.gpg [490 B]
Get:2 http://downloads-distro.mongodb.org dist Release [2,032 B]
Ign http://us.archive.ubuntu.com precise InRelease
Ign http://us.archive.ubuntu.com precise-updates InRelease
Ign http://us.archive.ubuntu.com precise-backports InRelease
Get:3 http://downloads-distro.mongodb.org dist/10gen amd64 Packages [16.7 kB]
Hit http://us.archive.ubuntu.com precise Release.gpg
Get:4 http://us.archive.ubuntu.com precise-updates Release.gpg [198 B]
Get:5 http://apt.basho.com precise InRelease [6,591 B]
Get:6 http://downloads-distro.mongodb.org dist/10gen i386 Packages [16.7 kB]
Ign http://downloads-distro.mongodb.org dist/10gen TranslationIndex
Get:7 http://us.archive.ubuntu.com precise-backports Release.gpg [198 B]
Get:8 http://apt.basho.com precise/main amd64 Packages [5,134 B]
Hit http://us.archive.ubuntu.com precise Release
Get:9 http://apt.postgresql.org precise-pgdg InRelease [33.7 kB]
Get:10 http://us.archive.ubuntu.com precise-updates Release [49.6 kB]
Hit http://apt.basho.com precise/main i386 Packages
Ign http://downloads-distro.mongodb.org dist/10gen Translation-en_US
Ign http://downloads-distro.mongodb.org dist/10gen Translation-en
Get:11 http://us.archive.ubuntu.com precise-backports Release [49.6 kB]
Get:12 http://www.rabbitmq.com testing InRelease [17.9 kB]
Ign http://apt.basho.com precise/main TranslationIndex
Hit http://us.archive.ubuntu.com precise/main Sources
Hit http://us.archive.ubuntu.com precise/restricted Sources
Hit http://us.archive.ubuntu.com precise/universe Sources
Hit http://us.archive.ubuntu.com precise/multiverse Sources
Hit http://us.archive.ubuntu.com precise/main amd64 Packages
Hit http://us.archive.ubuntu.com precise/restricted amd64 Packages
Hit http://us.archive.ubuntu.com precise/universe amd64 Packages
Hit http://us.archive.ubuntu.com precise/multiverse amd64 Packages
Hit http://us.archive.ubuntu.com precise/main i386 Packages
Hit http://us.archive.ubuntu.com precise/restricted i386 Packages
Hit http://us.archive.ubuntu.com precise/universe i386 Packages
Hit http://us.archive.ubuntu.com precise/multiverse i386 Packages
Hit http://us.archive.ubuntu.com precise/main TranslationIndex
Hit http://us.archive.ubuntu.com precise/multiverse TranslationIndex
Hit http://us.archive.ubuntu.com precise/restricted TranslationIndex
Hit http://us.archive.ubuntu.com precise/universe TranslationIndex
Get:13 http://us.archive.ubuntu.com precise-updates/main Sources [460 kB]
Ign http://ppa.launchpad.net precise InRelease
Ign http://ppa.launchpad.net precise InRelease
Get:14 http://apt.postgresql.org precise-pgdg/main amd64 Packages [48.3 kB]
Ign http://ppa.launchpad.net precise InRelease
Ign http://ppa.launchpad.net precise InRelease
Ign http://ppa.launchpad.net precise InRelease
Ign http://ppa.launchpad.net precise InRelease
Ign http://ppa.launchpad.net precise InRelease
Get:15 http://apt.postgresql.org precise-pgdg/main i386 Packages [48.5 kB]
Hit http://ppa.launchpad.net precise Release.gpg
Get:16 http://us.archive.ubuntu.com precise-updates/restricted Sources [8,056 B]
Get:17 http://us.archive.ubuntu.com precise-updates/universe Sources [107 kB]
Get:18 http://us.archive.ubuntu.com precise-updates/multiverse Sources [8,909 B]
Get:19 http://us.archive.ubuntu.com precise-updates/main amd64 Packages [789 kB]
Ign http://apt.postgresql.org precise-pgdg/main TranslationIndex
Get:20 http://us.archive.ubuntu.com precise-updates/restricted amd64 Packages [13.7 kB]
Get:21 http://us.archive.ubuntu.com precise-updates/universe amd64 Packages [241 kB]
Get:22 http://us.archive.ubuntu.com precise-updates/multiverse amd64 Packages [15.3 kB]
Get:23 http://us.archive.ubuntu.com precise-updates/main i386 Packages [822 kB]
Get:24 http://ppa.launchpad.net precise Release.gpg [316 B]
Get:25 http://ppa.launchpad.net precise Release.gpg [316 B]
Get:26 http://ppa.launchpad.net precise Release.gpg [316 B]
Get:27 http://ppa.launchpad.net precise Release.gpg [316 B]
Get:28 http://ppa.launchpad.net precise Release.gpg [316 B]
Get:29 http://us.archive.ubuntu.com precise-updates/restricted i386 Packages [13.7 kB]
Get:30 http://us.archive.ubuntu.com precise-updates/universe i386 Packages [247 kB]
Get:31 http://www.rabbitmq.com testing/main amd64 Packages [497 B]
Get:32 http://us.archive.ubuntu.com precise-updates/multiverse i386 Packages [15.5 kB]
Get:33 http://us.archive.ubuntu.com precise-updates/main TranslationIndex [3,564 B]
Get:34 http://us.archive.ubuntu.com precise-updates/multiverse TranslationIndex [2,605 B]
Get:35 http://us.archive.ubuntu.com precise-updates/restricted TranslationIndex [2,461 B]
Get:36 http://us.archive.ubuntu.com precise-updates/universe TranslationIndex [2,850 B]
Get:37 http://us.archive.ubuntu.com precise-backports/main Sources [5,145 B]
Get:38 http://us.archive.ubuntu.com precise-backports/restricted Sources [14 B]
Get:39 http://us.archive.ubuntu.com precise-backports/universe Sources [38.4 kB]
Get:40 http://us.archive.ubuntu.com precise-backports/multiverse Sources [5,311 B]
Get:41 http://us.archive.ubuntu.com precise-backports/main amd64 Packages [6,412 B]
Get:42 http://us.archive.ubuntu.com precise-backports/restricted amd64 Packages [14 B]
Get:43 http://us.archive.ubuntu.com precise-backports/universe amd64 Packages [41.4 kB]
Get:44 http://us.archive.ubuntu.com precise-backports/multiverse amd64 Packages [5,206 B]
Get:45 http://us.archive.ubuntu.com precise-backports/main i386 Packages [6,420 B]
Get:46 http://us.archive.ubuntu.com precise-backports/restricted i386 Packages [14 B]
Get:47 http://us.archive.ubuntu.com precise-backports/universe i386 Packages [41.2 kB]
Get:48 http://us.archive.ubuntu.com precise-backports/multiverse i386 Packages [5,178 B]
Get:49 http://us.archive.ubuntu.com precise-backports/main TranslationIndex [72 B]
Get:50 http://us.archive.ubuntu.com precise-backports/multiverse TranslationIndex [72 B]
Get:51 http://us.archive.ubuntu.com precise-backports/restricted TranslationIndex [70 B]
Get:52 http://us.archive.ubuntu.com precise-backports/universe TranslationIndex [73 B]
Hit http://us.archive.ubuntu.com precise/main Translation-en
Hit http://us.archive.ubuntu.com precise/multiverse Translation-en
Hit http://us.archive.ubuntu.com precise/restricted Translation-en
Hit http://us.archive.ubuntu.com precise/universe Translation-en
Get:53 http://us.archive.ubuntu.com precise-updates/main Translation-en [352 kB]
Get:54 http://www.rabbitmq.com testing/main i386 Packages [497 B]
Ign http://www.rabbitmq.com testing/main TranslationIndex
Hit http://us.archive.ubuntu.com precise-updates/multiverse Translation-en
Get:55 http://us.archive.ubuntu.com precise-updates/restricted Translation-en [3,027 B]
Get:56 http://us.archive.ubuntu.com precise-updates/universe Translation-en [140 kB]
Get:57 http://ppa.launchpad.net precise Release.gpg [316 B]
Hit http://us.archive.ubuntu.com precise-backports/main Translation-en
Hit http://us.archive.ubuntu.com precise-backports/multiverse Translation-en
Hit http://us.archive.ubuntu.com precise-backports/restricted Translation-en
Get:58 http://us.archive.ubuntu.com precise-backports/universe Translation-en [32.9 kB]
Ign http://apt.basho.com precise/main Translation-en_US
Ign http://apt.basho.com precise/main Translation-en
Hit http://ppa.launchpad.net precise Release
Get:59 http://ppa.launchpad.net precise Release [11.9 kB]
Get:60 http://ppa.launchpad.net precise Release [11.8 kB]
Get:61 http://ppa.launchpad.net precise Release [11.8 kB]
Ign http://ppa.launchpad.net precise Release
Get:62 http://ppa.launchpad.net precise Release [11.9 kB]
Ign http://apt.postgresql.org precise-pgdg/main Translation-en_US
Get:63 http://ppa.launchpad.net precise Release [11.9 kB]
Ign http://apt.postgresql.org precise-pgdg/main Translation-en
Get:64 http://ppa.launchpad.net precise Release [11.9 kB]
Hit http://ppa.launchpad.net precise/main amd64 Packages
Hit http://ppa.launchpad.net precise/main i386 Packages
Ign http://ppa.launchpad.net precise/main TranslationIndex
Get:65 http://ppa.launchpad.net precise/main amd64 Packages [5,142 B]
Get:66 http://ppa.launchpad.net precise/main i386 Packages [5,144 B]
Ign http://ppa.launchpad.net precise/main TranslationIndex
Get:67 http://ppa.launchpad.net precise/main Sources [6,621 B]
Get:68 http://ppa.launchpad.net precise/main amd64 Packages [7,340 B]
Get:69 http://ppa.launchpad.net precise/main i386 Packages [3,438 B]
Ign http://ppa.launchpad.net precise/main TranslationIndex
Get:70 http://ppa.launchpad.net precise/main amd64 Packages [886 B]
Get:71 http://ppa.launchpad.net precise/main i386 Packages [902 B]
Ign http://ppa.launchpad.net precise/main TranslationIndex
Get:72 http://ppa.launchpad.net precise/main amd64 Packages [1,719 B]
Get:73 http://ppa.launchpad.net precise/main i386 Packages [1,212 B]
Ign http://ppa.launchpad.net precise/main TranslationIndex
Get:74 http://ppa.launchpad.net precise/main amd64 Packages [35.8 kB]
Get:75 http://ppa.launchpad.net precise/main i386 Packages [35.8 kB]
Ign http://ppa.launchpad.net precise/main TranslationIndex
Get:76 http://ppa.launchpad.net precise/main amd64 Packages [2,803 B]
Ign http://www.rabbitmq.com testing/main Translation-en_US
Get:77 http://ppa.launchpad.net precise/main i386 Packages [2,803 B]
Ign http://ppa.launchpad.net precise/main TranslationIndex
Ign http://www.rabbitmq.com testing/main Translation-en
Ign http://ppa.launchpad.net precise/main Translation-en_US
Ign http://ppa.launchpad.net precise/main Translation-en
Ign http://ppa.launchpad.net precise/main Translation-en_US
Ign http://ppa.launchpad.net precise/main Translation-en
Ign http://ppa.launchpad.net precise/main Translation-en_US
Ign http://ppa.launchpad.net precise/main Translation-en
Ign http://ppa.launchpad.net precise/main Translation-en_US
Ign http://ppa.launchpad.net precise/main Translation-en
Ign http://ppa.launchpad.net precise/main Translation-en_US
Ign http://ppa.launchpad.net precise/main Translation-en
Ign http://ppa.launchpad.net precise/main Translation-en_US
Ign http://ppa.launchpad.net precise/main Translation-en
Ign http://ppa.launchpad.net precise/main Translation-en_US
Ign http://ppa.launchpad.net precise/main Translation-en
Ign http://security.ubuntu.com precise-security InRelease
Get:78 http://security.ubuntu.com precise-security Release.gpg [198 B]
Get:79 http://security.ubuntu.com precise-security Release [49.6 kB]
Get:80 http://security.ubuntu.com precise-security/main Sources [106 kB]
Get:81 http://security.ubuntu.com precise-security/restricted Sources [2,494 B]
Get:82 http://security.ubuntu.com precise-security/universe Sources [30.7 kB]
Get:83 http://security.ubuntu.com precise-security/multiverse Sources [1,795 B]
Get:84 http://security.ubuntu.com precise-security/main amd64 Packages [401 kB]
Get:85 http://security.ubuntu.com precise-security/restricted amd64 Packages [4,627 B]
Get:86 http://security.ubuntu.com precise-security/universe amd64 Packages [93.5 kB]
Get:87 http://security.ubuntu.com precise-security/multiverse amd64 Packages [2,434 B]
Get:88 http://security.ubuntu.com precise-security/main i386 Packages [427 kB]
Get:89 http://security.ubuntu.com precise-security/restricted i386 Packages [4,620 B]
Get:90 http://security.ubuntu.com precise-security/universe i386 Packages [98.7 kB]
Get:91 http://security.ubuntu.com precise-security/multiverse i386 Packages [2,647 B]
Get:92 http://security.ubuntu.com precise-security/main TranslationIndex [74 B]
Get:93 http://security.ubuntu.com precise-security/multiverse TranslationIndex [72 B]
Get:94 http://security.ubuntu.com precise-security/restricted TranslationIndex [72 B]
Get:95 http://security.ubuntu.com precise-security/universe TranslationIndex [73 B]
Get:96 http://security.ubuntu.com precise-security/main Translation-en [184 kB]
Hit http://security.ubuntu.com precise-security/multiverse Translation-en
Hit http://security.ubuntu.com precise-security/restricted Translation-en
Get:97 http://security.ubuntu.com precise-security/universe Translation-en [57.5 kB]
Fetched 5,382 kB in 10s (500 kB/s)
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FF3AEACEF6F88286
$ sudo apt-get install cabal-install-1.18 ghc-$GHCVER
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libgmp-dev libgmpxx4ldbl
Suggested packages:
  libgmp10-doc libmpfr-dev
The following NEW packages will be installed:
  cabal-install-1.18 ghc-7.6.3 libgmp-dev libgmpxx4ldbl
0 upgraded, 4 newly installed, 0 to remove and 176 not upgraded.
Need to get 57.7 MB of archives.
After this operation, 345 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  cabal-install-1.18 ghc-7.6.3
E: There are problems and -y was used without --force-yes
The command "sudo apt-get install cabal-install-1.18 ghc-$GHCVER" failed and exited with 100 during .
Your build has been stopped.
```

**Comment by seanparsons** [comment]
Oddly I've just experienced this issue too: https://travis-ci.org/seanparsons/ekg-core/jobs/56842589

**Comment by cheecheeo** [comment]
@seanparsons the link you provided was a successful run:
```
$ travis_retry sudo add-apt-repository -y ppa:hvr/ghc
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.9n0qM1xgLs --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//apt.postgresql.org.gpg --keyserver hkp://keyserver.ubuntu.com:80/ --recv 063DAB2BDC0B3F9FCEBC378BFF3AEACEF6F88286
gpg: requesting key F6F88286 from hkp server keyserver.ubuntu.com
gpg: key F6F88286: public key "Launchpad PPA for Herbert V. Riedel" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```

**Comment by seanparsons** [comment]
@cheecheeo I'm guessing because I retried the build, didn't realise it would overwrite the result.
